-- SurveyKe Survey Questions Seeder
-- Run this after the main setup to populate survey questions

-- Lifestyle surveys (50 questions)
INSERT INTO public.surveys (question, options, reward, category, order_index) VALUES
  ('Which mobile payment service do you use most often?', ARRAY['M-Pesa', 'Airtel Money', 'T-Kash', 'Bank App'], 30, 'lifestyle', 1),
  ('How often do you shop at local supermarkets per week?', ARRAY['Once', '2-3 times', '4-5 times', 'Daily'], 30, 'lifestyle', 2),
  ('What is your preferred social media platform?', ARRAY['WhatsApp', 'TikTok', 'Instagram', 'Facebook'], 30, 'lifestyle', 3),
  ('Which beverage brand do you prefer?', ARRAY['Coca-Cola', 'Tusker', 'Ketepa Tea', 'Del Monte Juice'], 30, 'lifestyle', 4),
  ('How do you primarily commute to work?', ARRAY['Matatu', 'Boda Boda', 'Personal Car', 'Walking'], 30, 'lifestyle', 5),
  ('What type of entertainment do you enjoy most?', ARRAY['Streaming', 'Local TV', 'Music', 'Sports'], 30, 'lifestyle', 6),
  ('Which food delivery service have you used?', ARRAY['Glovo', 'Uber Eats', 'Jumia Food', 'None'], 30, 'lifestyle', 7),
  ('How much do you spend on airtime monthly?', ARRAY['Under KSH 500', 'KSH 500-1000', 'KSH 1000-2000', 'Over KSH 2000'], 30, 'lifestyle', 8),
  ('Where do you mostly buy clothes?', ARRAY['Mitumba Markets', 'Branded Stores', 'Online Shops', 'Tailored'], 30, 'lifestyle', 9),
  ('How often do you eat out per week?', ARRAY['Never', '1-2 times', '3-4 times', '5+ times'], 30, 'lifestyle', 10),
  ('Preferred weekend activity?', ARRAY['Family time', 'Outdoor sports', 'Movies', 'Travel'], 30, 'lifestyle', 11),
  ('Favourite local fast food?', ARRAY['KFC', 'Galitos', 'Java', 'Local kibandas'], 30, 'lifestyle', 12),
  ('Which supermarket chain do you prefer?', ARRAY['Naivas', 'Carrefour', 'Quickmart', 'Cleanshelf'], 30, 'lifestyle', 13),
  ('Do you shop online?', ARRAY['Weekly', 'Monthly', 'Rarely', 'Never'], 30, 'lifestyle', 14),
  ('Preferred mode of payment in shops?', ARRAY['M-Pesa', 'Cash', 'Card', 'Bank transfer'], 30, 'lifestyle', 15),
  ('How often do you visit a hairdresser/barber?', ARRAY['Weekly', 'Monthly', 'Every 2-3 months', 'Rarely'], 30, 'lifestyle', 16),
  ('What type of milk do you buy most?', ARRAY['Fresh milk', 'Powdered milk', 'Long-life milk', 'Plant-based milk'], 30, 'lifestyle', 17),
  ('Which bread brand do you prefer?', ARRAY['Broadways', 'Superloaf', 'Mini Baker', 'Homemade'], 30, 'lifestyle', 18),
  ('How do you watch news?', ARRAY['TV', 'Radio', 'Social media', 'Online news sites'], 30, 'lifestyle', 19),
  ('Preferred mode of transport for long distance?', ARRAY['Bus', 'SGR Train', 'Flight', 'Personal car'], 30, 'lifestyle', 20),
  ('Which mobile network do you use?', ARRAY['Safaricom', 'Airtel', 'Telkom', 'Faiba'], 30, 'lifestyle', 21),
  ('How do you save contacts?', ARRAY['Phone memory', 'SIM card', 'Google account', 'iCloud'], 30, 'lifestyle', 22),
  ('Which messaging app do you use most?', ARRAY['WhatsApp', 'SMS', 'Telegram', 'Signal'], 30, 'lifestyle', 23),
  ('How do you backup your phone data?', ARRAY['Google Drive', 'iCloud', 'Computer', 'I don''t backup'], 30, 'lifestyle', 24),
  ('Which TV package do you have?', ARRAY['DStv', 'GOtv', 'Zuku', 'Free-to-air'], 30, 'lifestyle', 25),
  ('How do you recharge your TV subscription?', ARRAY['M-Pesa', 'Bank app', 'Agent', 'Online'], 30, 'lifestyle', 26),
  ('Which cooking gas do you use?', ARRAY['Total Gas', 'K-Gas', 'Hashi Gas', 'Other'], 30, 'lifestyle', 27),
  ('Where do you buy cooking gas?', ARRAY['Supermarket', 'Gas depot', 'Door-to-door vendor', 'Petrol station'], 30, 'lifestyle', 28),
  ('How often do you change your phone?', ARRAY['Every year', 'Every 2 years', 'Every 3+ years', 'When it breaks'], 30, 'lifestyle', 29),
  ('Where do you buy your phone?', ARRAY['Official store', 'Online shop', 'Second-hand market', 'From friends/family'], 30, 'lifestyle', 30),
  ('Do you use mobile banking?', ARRAY['Yes, daily', 'Yes, weekly', 'Yes, monthly', 'No'], 30, 'lifestyle', 31),
  ('Which bank do you use most?', ARRAY['KCB', 'Equity', 'Cooperative', 'Other'], 30, 'lifestyle', 32),
  ('How do you pay your rent?', ARRAY['M-Pesa', 'Bank transfer', 'Cash', 'Cheque'], 30, 'lifestyle', 33),
  ('Which electricity provider do you use?', ARRAY['Kenya Power', 'Solar', 'Generator', 'Other'], 30, 'lifestyle', 34),
  ('How do you buy electricity tokens?', ARRAY['M-Pesa', 'Bank app', 'Agent', 'Online'], 30, 'lifestyle', 35),
  ('Do you have home internet?', ARRAY['Yes, fiber', 'Yes, wireless', 'Mobile hotspot', 'No'], 30, 'lifestyle', 36),
  ('Which home internet provider?', ARRAY['Safaricom', 'Zuku', 'Faiba', 'Airtel'], 30, 'lifestyle', 37),
  ('How do you listen to music?', ARRAY['Streaming apps', 'Radio', 'Downloaded music', 'YouTube'], 30, 'lifestyle', 38),
  ('Which music streaming app?', ARRAY['Spotify', 'Boomplay', 'YouTube Music', 'Apple Music'], 30, 'lifestyle', 39),
  ('How do you watch movies?', ARRAY['Cinema', 'Streaming at home', 'DVD/Flash', 'Downloaded'], 30, 'lifestyle', 40),
  ('Which movie streaming service?', ARRAY['Netflix', 'Showmax', 'Amazon Prime', 'YouTube'], 30, 'lifestyle', 41),
  ('Do you play video games?', ARRAY['Yes, console', 'Yes, mobile', 'Yes, PC', 'No'], 30, 'lifestyle', 42),
  ('Which gaming console do you have?', ARRAY['PlayStation', 'Xbox', 'Nintendo', 'None'], 30, 'lifestyle', 43),
  ('How often do you travel upcountry?', ARRAY['Monthly', 'Every 3 months', 'Yearly', 'Rarely'], 30, 'lifestyle', 44),
  ('Which bus company do you prefer?', ARRAY['Easy Coach', 'Guardian Angel', 'Ena Coach', 'Other'], 30, 'lifestyle', 45),
  ('Do you have a loyalty card?', ARRAY['Yes, supermarket', 'Yes, petrol station', 'Yes, airline', 'No'], 30, 'lifestyle', 46),
  ('How do you send money upcountry?', ARRAY['M-Pesa', 'Bank transfer', 'Bus parcel', 'Send with someone'], 30, 'lifestyle', 47),
  ('Which funeral insurance do you have?', ARRAY['None', 'APA', 'CIC', 'Other'], 30, 'lifestyle', 48),
  ('How do you pay for NHIF?', ARRAY['M-Pesa', 'Bank', 'Employer', 'Agent'], 30, 'lifestyle', 49),
  ('Do you have a written will?', ARRAY['Yes', 'No', 'Thinking about it', 'Not applicable'], 30, 'lifestyle', 50);

-- Tech surveys (50 questions)
INSERT INTO public.surveys (question, options, reward, category, order_index) VALUES
  ('What smartphone brand do you currently use?', ARRAY['Samsung', 'Tecno/Infinix', 'iPhone', 'Other'], 30, 'tech', 1),
  ('Which internet provider do you prefer?', ARRAY['Safaricom', 'Airtel', 'Telkom', 'Faiba'], 30, 'tech', 2),
  ('How many hours do you spend online daily?', ARRAY['1-2', '3-5', '6-8', '8+'], 30, 'tech', 3),
  ('Primary use of internet?', ARRAY['Social Media', 'Work', 'Education', 'Entertainment'], 30, 'tech', 4),
  ('Which fintech app do you use?', ARRAY['Tala', 'Branch', 'Fuliza', 'None'], 30, 'tech', 5),
  ('Preferred online marketplace?', ARRAY['Jumia', 'Kilimall', 'Jiji', 'None'], 30, 'tech', 6),
  ('How do you secure your phone?', ARRAY['Fingerprint', 'PIN', 'Face ID', 'None'], 30, 'tech', 7),
  ('Cloud storage of choice?', ARRAY['Google Drive', 'iCloud', 'Dropbox', 'None'], 30, 'tech', 8),
  ('Streaming subscription?', ARRAY['Netflix', 'Showmax', 'YouTube Premium', 'None'], 30, 'tech', 9),
  ('How often do you update apps?', ARRAY['Auto', 'Weekly', 'Monthly', 'Rarely'], 30, 'tech', 10),
  ('Do you own a laptop?', ARRAY['Yes - Windows', 'Yes - Mac', 'Yes - Chromebook', 'No'], 30, 'tech', 11),
  ('Use of AI tools (e.g. ChatGPT)?', ARRAY['Daily', 'Weekly', 'Tried it', 'Never'], 30, 'tech', 12),
  ('Preferred browser?', ARRAY['Chrome', 'Safari', 'Firefox', 'Edge'], 30, 'tech', 13),
  ('Mobile data bundle frequency?', ARRAY['Daily', 'Weekly', 'Monthly', 'Wi-Fi only'], 30, 'tech', 14),
  ('Have you bought online?', ARRAY['Often', 'Sometimes', 'Once', 'Never'], 30, 'tech', 15),
  ('Which email service do you use?', ARRAY['Gmail', 'Outlook', 'Yahoo', 'Other'], 30, 'tech', 16),
  ('Do you use a password manager?', ARRAY['Yes, regularly', 'Yes, sometimes', 'No, but want to', 'No'], 30, 'tech', 17),
  ('Which video calling app?', ARRAY['Zoom', 'Google Meet', 'Microsoft Teams', 'WhatsApp'], 30, 'tech', 18),
  ('Do you use VPN?', ARRAY['Yes, daily', 'Yes, sometimes', 'No, but want to', 'No'], 30, 'tech', 19),
  ('Which social media do you post on most?', ARRAY['Instagram', 'TikTok', 'Twitter/X', 'Facebook'], 30, 'tech', 20),
  ('Do you edit photos/videos?', ARRAY['Yes, professionally', 'Yes, casually', 'No, but want to', 'No'], 30, 'tech', 21),
  ('Which photo editing app?', ARRAY['Adobe Lightroom', 'VSCO', 'Snapseed', 'Canva'], 30, 'tech', 22),
  ('How do you transfer files?', ARRAY['Email', 'WhatsApp', 'Cloud', 'Bluetooth/Xender'], 30, 'tech', 23),
  ('Which OS do you prefer?', ARRAY['Android', 'iOS', 'Windows', 'Mac'], 30, 'tech', 24),
  ('Do you code/program?', ARRAY['Yes, professionally', 'Yes, as hobby', 'Learning', 'No'], 30, 'tech', 25),
  ('Which programming language?', ARRAY['JavaScript', 'Python', 'Java', 'Other'], 30, 'tech', 26),
  ('Do you use digital wallets?', ARRAY['M-Pesa', 'Apple Pay', 'Google Pay', 'None'], 30, 'tech', 27),
  ('Which crypto do you know?', ARRAY['Bitcoin', 'Ethereum', 'None', 'Other'], 30, 'tech', 28),
  ('Have you bought crypto?', ARRAY['Yes, holding', 'Yes, sold', 'No, interested', 'No'], 30, 'tech', 29),
  ('Which trading app?', ARRAY['Etoro', 'Robinhood', 'Binance', 'None'], 30, 'tech', 30),
  ('Do you read tech news?', ARRAY['Daily', 'Weekly', 'Monthly', 'Never'], 30, 'tech', 31),
  ('Which tech news source?', ARRAY['TechCrunch', 'The Verge', 'Local blogs', 'Social media'], 30, 'tech', 32),
  ('Do you use smart home devices?', ARRAY['Yes, multiple', 'Yes, a few', 'No, want to', 'No'], 30, 'tech', 33),
  ('Which smart assistant?', ARRAY['Google Assistant', 'Siri', 'Alexa', 'None'], 30, 'tech', 34),
  ('Do you have a smart TV?', ARRAY['Yes, Android TV', 'Yes, other', 'No, but want', 'No'], 30, 'tech', 35),
  ('How do you cast to TV?', ARRAY['Chromecast', 'Screen mirroring', 'HDMI cable', 'Don''t cast'], 30, 'tech', 36),
  ('Which fitness tracker?', ARRAY['Mi Band', 'Fitbit', 'Apple Watch', 'None'], 30, 'tech', 37),
  ('Do you use ride apps?', ARRAY['Uber', 'Bolt', 'Little', 'None'], 30, 'tech', 38),
  ('Which food delivery app?', ARRAY['Glovo', 'Uber Eats', 'Jumia Food', 'None'], 30, 'tech', 39),
  ('Do you book flights online?', ARRAY['Always', 'Sometimes', 'Through agent', 'Never'], 30, 'tech', 40),
  ('Which travel booking site?', ARRAY['Travelstart', 'Expedia', 'Airline site', 'Agent'], 30, 'tech', 41),
  ('Do you use LinkedIn?', ARRAY['Daily', 'Weekly', 'Monthly', 'Never'], 30, 'tech', 42),
  ('How do you find jobs?', ARRAY['LinkedIn', 'Job sites', 'Referrals', 'Newspaper'], 30, 'tech', 43),
  ('Which freelancing platform?', ARRAY['Upwork', 'Fiverr', 'Local platforms', 'None'], 30, 'tech', 44),
  ('Do you take online courses?', ARRAY['Yes, regularly', 'Yes, sometimes', 'No, want to', 'No'], 30, 'tech', 45),
  ('Which learning platform?', ARRAY['Coursera', 'Udemy', 'YouTube', 'Other'], 30, 'tech', 46),
  ('Do you use e-books?', ARRAY['Yes, Kindle', 'Yes, other app', 'No, prefer physical', 'No'], 30, 'tech', 47),
  ('Which podcast app?', ARRAY['Spotify', 'Apple Podcasts', 'Google Podcasts', 'None'], 30, 'tech', 48),
  ('Do you game online?', ARRAY['Yes, competitively', 'Yes, casually', 'No, but want to', 'No'], 30, 'tech', 49),
  ('Which gaming platform?', ARRAY['Steam', 'Epic Games', 'Mobile games', 'Console'], 30, 'tech', 50);

-- Health surveys (50 questions, higher reward)
INSERT INTO public.surveys (question, options, reward, category, order_index) VALUES
  ('How often do you visit a doctor per year?', ARRAY['Never', 'Once', '2-3', '4+'], 40, 'health', 1),
  ('Do you have health insurance?', ARRAY['NHIF only', 'Private', 'Both', 'None'], 40, 'health', 2),
  ('Rating of public healthcare?', ARRAY['Excellent', 'Good', 'Average', 'Poor'], 40, 'health', 3),
  ('Primary water source?', ARRAY['Tap', 'Borehole', 'Bottled', 'Rain'], 40, 'health', 4),
  ('Exercise per week?', ARRAY['Never', '1-2', '3-4', 'Daily'], 40, 'health', 5),
  ('Biggest health concern?', ARRAY['Malaria', 'Diabetes', 'Mental Health', 'HIV/AIDS'], 40, 'health', 6),
  ('Use telemedicine?', ARRAY['Regularly', 'Sometimes', 'Once', 'Never'], 40, 'health', 7),
  ('Where do you buy medication?', ARRAY['Hospital', 'Private pharmacy', 'Online', 'Traditional'], 40, 'health', 8),
  ('NHIF satisfaction?', ARRAY['Very', 'Yes', 'Neutral', 'No'], 40, 'health', 9),
  ('What motivates healthy living?', ARRAY['Family', 'Looks', 'Energy', 'Doctor'], 40, 'health', 10),
  ('Daily fruit & veg?', ARRAY['Always', 'Often', 'Rarely', 'Never'], 40, 'health', 11),
  ('Sleep hours per night?', ARRAY['<5', '5-6', '7-8', '8+'], 40, 'health', 12),
  ('Stress levels?', ARRAY['Low', 'Moderate', 'High', 'Severe'], 40, 'health', 13),
  ('Smoking status?', ARRAY['Never', 'Quit', 'Occasional', 'Daily'], 40, 'health', 14),
  ('Routine medical checkups?', ARRAY['Yearly', 'Every 2yrs', 'Rarely', 'Never'], 40, 'health', 15),
  ('Alcohol consumption?', ARRAY['Never', 'Socially', 'Weekly', 'Daily'], 40, 'health', 16),
  ('Weight management goal?', ARRAY['Lose weight', 'Maintain', 'Gain weight', 'No goal'], 40, 'health', 17),
  ('Do you track your health?', ARRAY['Yes, with apps', 'Yes, manually', 'No, but want to', 'No'], 40, 'health', 18),
  ('Which health app?', ARRAY['Samsung Health', 'Apple Health', 'Google Fit', 'Other'], 40, 'health', 19),
  ('Mental health support?', ARRAY['Therapist', 'Support groups', 'Friends/family', 'None'], 40, 'health', 20),
  ('Do you meditate?', ARRAY['Daily', 'Weekly', 'Sometimes', 'Never'], 40, 'health', 21),
  ('Preferred workout time?', ARRAY['Morning', 'Afternoon', 'Evening', 'No preference'], 40, 'health', 22),
  ('Gym membership?', ARRAY['Active', 'Expired', 'Thinking about it', 'No'], 40, 'health', 23),
  ('Home workout equipment?', ARRAY['Yes, full setup', 'Yes, basic', 'No, but want', 'No'], 40, 'health', 24),
  ('Sports participation?', ARRAY['Team sports', 'Individual', 'Recreational', 'None'], 40, 'health', 25),
  ('Dietary restrictions?', ARRAY['Vegetarian', 'Diabetic diet', 'Religious', 'None'], 40, 'health', 26),
  ('Supplement usage?', ARRAY['Daily', 'Weekly', 'Sometimes', 'Never'], 40, 'health', 27),
  ('Which supplements?', ARRAY['Multivitamins', 'Vitamin C/D', 'Protein', 'None'], 40, 'health', 28),
  ('Sleep quality?', ARRAY['Excellent', 'Good', 'Fair', 'Poor'], 40, 'health', 29),
  ('Sleep aid usage?', ARRAY['Never', 'Sometimes', 'Often', 'Every night'], 40, 'health', 30),
  ('Screen time concern?', ARRAY['Very concerned', 'Somewhat', 'Not really', 'Not at all'], 40, 'health', 31),
  ('Digital detox attempts?', ARRAY['Regularly', 'Sometimes', 'Once', 'Never'], 40, 'health', 32),
  ('Work-life balance?', ARRAY['Excellent', 'Good', 'Fair', 'Poor'], 40, 'health', 33),
  ('Burnout experience?', ARRAY['Currently', 'Recently', 'In the past', 'Never'], 40, 'health', 34),
  ('Eating disorder history?', ARRAY['Currently', 'Recovered', 'Suspected', 'Never'], 40, 'health', 35),
  ('Body image satisfaction?', ARRAY['Very satisfied', 'Satisfied', 'Neutral', 'Dissatisfied'], 40, 'health', 36),
  ('Vaccination status?', ARRAY['Fully vaccinated', 'Partially', 'Planning to', 'Declined'], 40, 'health', 37),
  ('COVID-19 impact?', ARRAY['Major impact', 'Moderate', 'Minor', 'None'], 40, 'health', 38),
  ('Chronic conditions?', ARRAY['Diabetes', 'Hypertension', 'Asthma', 'None'], 40, 'health', 39),
  ('Family health history?', ARRAY['Heart disease', 'Cancer', 'Diabetes', 'None known'], 40, 'health', 40),
  ('Health information source?', ARRAY['Doctor', 'Internet', 'Family/friends', 'Social media'], 40, 'health', 41),
  ('Alternative medicine?', ARRAY['Traditional herbs', 'Acupuncture', 'Homeopathy', 'None'], 40, 'health', 42),
  ('Hospital preference?', ARRAY['Public', 'Private', 'Mission', 'Any'], 40, 'health', 43),
  ('Emergency preparedness?', ARRAY['Fully prepared', 'Somewhat', 'Not really', 'Not at all'], 40, 'health', 44),
  ('First aid knowledge?', ARRAY['Certified', 'Basic', 'Minimal', 'None'], 40, 'health', 45),
  ('Health insurance satisfaction?', ARRAY['Very satisfied', 'Satisfied', 'Neutral', 'Dissatisfied'], 40, 'health', 46),
  ('Medical debt experience?', ARRAY['Currently', 'In the past', 'Concerned about', 'Never'], 40, 'health', 47),
  ('Healthcare affordability?', ARRAY['Very affordable', 'Affordable', 'Struggling', 'Unaffordable'], 40, 'health', 48),
  ('Health goal for 2024?', ARRAY['Lose weight', 'Get fit', 'Eat better', 'No specific goal'], 40, 'health', 49),
  ('Wellness app interest?', ARRAY['Very interested', 'Somewhat', 'Not really', 'Not at all'], 40, 'health', 50);

-- Finance surveys (50 questions, highest reward)
INSERT INTO public.surveys (question, options, reward, category, order_index) VALUES
  ('How do you primarily save?', ARRAY['M-Pesa', 'Bank', 'Chama/Sacco', 'Cash'], 50, 'finance', 1),
  ('Taken a mobile loan?', ARRAY['M-Shwari', 'Tala/Branch', 'Fuliza', 'Never'], 50, 'finance', 2),
  ('Biggest monthly expense?', ARRAY['Rent', 'Food', 'Transport', 'School fees'], 50, 'finance', 3),
  ('Investment of choice?', ARRAY['T-Bills', 'NSE Stocks', 'Crypto', 'None'], 50, 'finance', 4),
  ('Monthly savings?', ARRAY['<1k', '1-5k', '5-10k', '10k+'], 50, 'finance', 5),
  ('Where would you invest 100k?', ARRAY['Real estate', 'Business', 'Stocks', 'Savings'], 50, 'finance', 6),
  ('How do you track expenses?', ARRAY['M-Pesa stmt', 'Excel', 'App', 'Don''t'], 50, 'finance', 7),
  ('Most important bank feature?', ARRAY['Low charges', 'Mobile banking', 'Loans', 'Interest'], 50, 'finance', 8),
  ('Sacco membership?', ARRAY['Active', 'Past', 'Interested', 'No'], 50, 'finance', 9),
  ('Inflation impact?', ARRAY['Significant', 'Moderate', 'Slight', 'None'], 50, 'finance', 10),
  ('Have an emergency fund?', ARRAY['Yes - 6mo', 'Yes - <6mo', 'Building', 'None'], 50, 'finance', 11),
  ('Use crypto?', ARRAY['Trade', 'Hold', 'Tried', 'Never'], 50, 'finance', 12),
  ('Insurance besides health?', ARRAY['Life', 'Motor', 'Education', 'None'], 50, 'finance', 13),
  ('Side hustle income?', ARRAY['Yes - main', 'Yes - extra', 'Planning', 'No'], 50, 'finance', 14),
  ('Retirement plan?', ARRAY['NSSF + private', 'NSSF only', 'Personal savings', 'None'], 50, 'finance', 15),
  ('Credit score awareness?', ARRAY['Know my score', 'Checked once', 'Heard of it', 'What''s that?'], 50, 'finance', 16),
  ('Credit card usage?', ARRAY['Multiple cards', 'One card', 'Debit only', 'Cash only'], 50, 'finance', 17),
  ('Loan repayment status?', ARRAY['All paid', 'Some pending', 'Struggling', 'Never taken'], 50, 'finance', 18),
  ('Financial advisor use?', ARRAY['Regularly', 'Once', 'No, but want', 'No'], 50, 'finance', 19),
  ('Budget adherence?', ARRAY['Always', 'Usually', 'Sometimes', 'Never'], 50, 'finance', 20),
  ('Debt-to-income ratio?', ARRAY['<10%', '10-30%', '30-50%', '>50%'], 50, 'finance', 21),
  ('Financial stress level?', ARRAY['None', 'Low', 'Moderate', 'High'], 50, 'finance', 22),
  ('Money personality?', ARRAY['Saver', 'Spender', 'Investor', 'Avoider'], 50, 'finance', 23),
  ('Biggest financial fear?', ARRAY['Job loss', 'Medical emergency', 'Retirement', 'Market crash'], 50, 'finance', 24),
  ('Financial education source?', ARRAY['School', 'Internet', 'Family', 'Professional'], 50, 'finance', 25),
  ('Stock market participation?', ARRAY['Active trader', 'Long-term investor', 'Want to start', 'Not interested'], 50, 'finance', 26),
  ('Government bond interest?', ARRAY['Very interested', 'Somewhat', 'Heard of it', 'No'], 50, 'finance', 27),
  ('Real estate ownership?', ARRAY['Own home', 'Rental property', 'Land only', 'None'], 50, 'finance', 28),
  ('Mortgage status?', ARRAY['Paying mortgage', 'Paid off', 'Considering', 'Renting'], 50, 'finance', 29),
  ('Car ownership status?', ARRAY['Fully paid', 'Financed', 'Company car', 'No car'], 50, 'finance', 30),
  ('Transport budget %?', ARRAY['<10%', '10-20%', '20-30%', '>30%'], 50, 'finance', 31),
  ('Food budget %?', ARRAY['<20%', '20-30%', '30-40%', '>40%'], 50, 'finance', 32),
  ('Housing budget %?', ARRAY['<30%', '30-40%', '40-50%', '>50%'], 50, 'finance', 33),
  ('Black tax experience?', ARRAY['Significant', 'Moderate', 'Minimal', 'None'], 50, 'finance', 34),
  ('Family financial support?', ARRAY['Yes, regularly', 'Yes, sometimes', 'Rarely', 'No'], 50, 'finance', 35),
  ('Children education fund?', ARRAY['Well funded', 'Building it', 'Starting', 'Not yet'], 50, 'finance', 36),
  ('Wedding fund status?', ARRAY['Fully funded', 'Building', 'Planning', 'Not applicable'], 50, 'finance', 37),
  ('Funeral preparedness?', ARRAY['Fully prepared', 'Some savings', 'Concerned', 'Not prepared'], 50, 'finance', 38),
  ('Financial goal 2024?', ARRAY['Buy property', 'Start business', 'Clear debt', 'Save more'], 50, 'finance', 39),
  ('Investment risk tolerance?', ARRAY['High', 'Moderate', 'Low', 'None'], 50, 'finance', 40),
  ('Preferred investment term?', ARRAY['Short (<1yr)', 'Medium (1-5yr)', 'Long (5+yr)', 'Very long (10+yr)'], 50, 'finance', 41),
  ('Dividend vs growth?', ARRAY['Dividend income', 'Capital growth', 'Both equally', 'Not sure'], 50, 'finance', 42),
  ('Unit trust interest?', ARRAY['Very interested', 'Somewhat', 'Heard of it', 'No'], 50, 'finance', 43),
  ('Pension awareness?', ARRAY['Very aware', 'Somewhat', 'Minimal', 'None'], 50, 'finance', 44),
  ('Tax planning strategy?', ARRAY['Professional help', 'Self-managed', 'No strategy', 'Not applicable'], 50, 'finance', 45),
  ('Digital payment preference?', ARRAY['Mobile money', 'Cards', 'Bank transfer', 'Cash'], 50, 'finance', 46),
  ('CBK digital currency interest?', ARRAY['Very interested', 'Somewhat', 'Heard of it', 'No'], 50, 'finance', 47),
  ('Financial app usage?', ARRAY['Multiple apps', 'A few apps', 'Bank app only', 'None'], 50, 'finance', 48),
  ('Fraud awareness level?', ARRAY['Very aware', 'Somewhat', 'Basic', 'Not aware'], 50, 'finance', 49),
  ('Wealth building priority?', ARRAY['Top priority', 'Important', 'Somewhat', 'Not priority'], 50, 'finance', 50);
